#!/usr/bin/env python3
"""Send a one-time email digest with latest skill outputs."""

import argparse
import asyncio
import json
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))

from enterprise_skills_lib.sensing.email_digest import send_report_email, is_smtp_configured
from enterprise_skills_lib.skill_envelope import load_latest_skill_output


SKILL_DIR_MAP = {
    "tech_sensing": "sensing",
    "competitive_intel": "competitive",
    "patent_monitor": "patents",
    "regulation_tracker": "regulations",
    "talent_radar": "talent",
    "executive_brief": "briefs",
}


def _build_digest_html(user_id: str, skills: list[str], domain: str) -> str:
    """Build an HTML digest from latest skill outputs."""
    sections = []

    for skill in skills:
        skill_dir = SKILL_DIR_MAP.get(skill, skill)
        envelope = load_latest_skill_output(skill_dir, user_id)

        if envelope:
            report = envelope.report
        else:
            # Try legacy format
            dir_path = os.path.join("data", user_id, skill_dir)
            if not os.path.isdir(dir_path):
                continue
            files = sorted(
                [f for f in os.listdir(dir_path) if f.startswith("report_") and f.endswith(".json")],
                key=lambda f: os.path.getmtime(os.path.join(dir_path, f)),
                reverse=True,
            )
            if not files:
                continue
            with open(os.path.join(dir_path, files[0]), "r", encoding="utf-8") as f:
                report = json.load(f)

        # Extract summary
        title = report.get("report_title", report.get("brief_title", skill.replace("_", " ").title()))
        summary = report.get("executive_summary", report.get("situation_summary", ""))[:500]

        sections.append(f"""
        <div style="margin-bottom: 24px; padding: 16px; border-left: 4px solid #2E86AB; background: #f8f9fa;">
            <h2 style="color: #1B2A4A; margin: 0 0 8px 0;">{title}</h2>
            <p style="color: #333; line-height: 1.6;">{summary}</p>
        </div>
        """)

    if not sections:
        return "<p>No skill outputs available for this digest.</p>"

    html = f"""
    <html>
    <body style="font-family: Calibri, Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
        <div style="background: #1B2A4A; color: white; padding: 24px; border-radius: 8px 8px 0 0;">
            <h1 style="margin: 0;">Enterprise Intelligence Digest</h1>
            <p style="margin: 8px 0 0 0; color: #2E86AB;">{domain}</p>
        </div>
        <div style="padding: 24px; border: 1px solid #ddd; border-top: none;">
            {''.join(sections)}
        </div>
        <div style="padding: 12px; text-align: center; color: #999; font-size: 12px;">
            Generated by CoPaw Enterprise Skills Platform
        </div>
    </body>
    </html>
    """
    return html


async def main():
    parser = argparse.ArgumentParser(description="Send email digest")
    parser.add_argument("--to", required=True, help="Recipient email address")
    parser.add_argument("--skills", default="tech_sensing",
                        help="Comma-separated skill names to include")
    parser.add_argument("--user-id", default="default")
    parser.add_argument("--domain", default="Generative AI")
    args = parser.parse_args()

    if not is_smtp_configured():
        print(json.dumps({
            "status": "error",
            "message": "SMTP not configured. Set SMTP_HOST, SMTP_USER, SMTP_PASSWORD env vars.",
        }))
        return

    skills = [s.strip() for s in args.skills.split(",")]

    html_body = _build_digest_html(args.user_id, skills, args.domain)

    subject = f"Intelligence Digest: {args.domain}"

    await send_report_email(
        to_email=args.to,
        subject=subject,
        html_body=html_body,
    )

    print(json.dumps({
        "status": "success",
        "sent_to": args.to,
        "skills_included": skills,
    }))


if __name__ == "__main__":
    asyncio.run(main())
